version: '3'

services:
        django:
                build: ./api
                command: ["python3", "manage.py", "runserver"]
                volumes:
                        - ./api:/app/api
        frontend:
                build: ./frontend
                command: ["npm", "start"]
                volumes:
                        - ./frontend:/app/frontend
                ports:
                        - "3000:3000"
volumes:
        node-modules:
                

